version: '3.4'

services:
  checkinservice:
    image: checkinservice
    build:
      context: .
      dockerfile: Checkin.Service/Dockerfile
    ports:
      - 8000:8000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AccountDb=Server=sqlserver;Database=AccountDB;User Id=sa;Password=${SA_PASSWORD};
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - 1433:1433
