version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - "10001:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "account_test"

  nats:
    image: 'nats:latest'
    command:
      - "--jetstream"
    ports:
      - "8222:8222"
      - "4222:4222"
